osu_key: stub
vk_personal_audio_token: stub

spotify: null

discord:
  status:
  - In development
  token: VAULT->dev/raccoonbot/alpha_token
  personal_id: stub

orca:
  address: localhost:8590

genius_token: stub
gachi_things: []

db:
  host: 127.0.0.1
  port: 3306
  user: root
  password: local
  db: raccoonbot
