osu_key: VAULT->raccoonbot/osu_key
vk_personal_audio_token: VAULT->raccoonbot/vk_personal_audio_token

spotify: VAULT->raccoonbot/spotify

discord:
  status: VAULT->raccoonbot/discord_status
  token: VAULT->raccoonbot/token
  personal_id: VAULT->raccoonbot/personal_id

orca:
  address: orca.virtual.consul:8590

genius_token: VAULT->raccoonbot/genius_token
gachi_things: VAULT->raccoonbot/gachi_things

db: VAULT->raccoonbot/db_connection_profile
